services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - nest
    healthcheck:
      test: 
        [
          "CMD-SHELL", 
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: napi
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./logs:/app/logs
      - ./prisma:/app/prisma
      - ./src:/app/src
      - node_modules:/app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
   
    networks:
      - nest

  redis:
    image: redis:alpine
    volumes:
      - nestjs_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - nest


volumes:
  postgres_data:
  nestjs_redis:
  node_modules:

networks:
  nest:
    driver: bridge